Catching ``Exception`` seems like an efficient way to handle multiple possible exceptions. Unfortunately, it traps all exception types, both checked and runtime exceptions, thereby casting too broad a net. Indeed, was it really the intention of developers to also catch runtime exceptions? To prevent any misunderstanding, if both checked and runtime exceptions are really expected to be caught, they should be explicitly listed in the ``catch`` clause.

This rule raises an issue if ``Exception`` is caught when it is not explicitly thrown by a method in the ``try`` block.
